language: node_js
node_js:
- node
install:
- yarn
script:
- npm run beforebuild
- npm run build
- npm run test
after_script:
- cat coverage/lcov.info | ./node_modules/.bin/coveralls
before_install:
  - yarn
deploy:
  provider: npm
  skip_cleanup: true
  email: kkitokkito@gmail.com
  api_key:
    secure: Q35vqCqXuoMRNpoXmy8CSCjx8hgx+Ul7NO/WI9EEr0WNWh1m16V62XLAmb9qBvEbPrL4b/balJpPlWi+a7OqXKEgYg7ccVdW1Jm0TX6Tt7qRoa7NJ3IKpGzcRpvMQvCr7Tks3/ZYeXQHKr6puakqmEMZQrfxa7blLWEUQxAGze3Qz9zmki7rios1FOCQz89UzIkO8uEDa4wNd5oUmTMGR0/S253Zx5eWLarr0Zp83lck/jNQZHVNkCtvIo5ac/O0JtuhgXmmCquTX7B8E5v3HVTXv1LQn3SjcYJ10ep5iHfzUC9tktIlMUfkyk+2ZWvNEJIEkA1ekqR2OjQLbJYLr29LxBbZXm14JXBJkiX/LlgKQuOied1diwIpz8DFnqyY0OKD6tbQzsdj5ap4gHRftXflldfdV1/IwoRrRnlgex8FWTztKZ8KP4zHTGeMJQsnbw5aQMxUSHETld0xAinCsOQHMjQwK9Gr2QzAVn5Xl58aAW//woqSTFOPxWv5He88ltEks0qpO9k3grsRKq3CQuWkV47Zpx/8W97ud/jKydIgI9d8DARY59MUSjn/qaZjLdzQeZLJmltXj3Ktfgb/ApbdFTF3G3DzrR8V2ReuR50tyKLlacY5Ea+cVOrSGz+Thd9pG4DM5kVgCkm3vOIaY+osVpV2p7cy45TqjxJ3fNA=
  on:
    tags: true
    repo: kkito/transmission-rpc
