language: node_js
node_js:
- node
install:
- yarn
script:
- npm run build
- npm run test
after_script:
- cat coverage/lcov.info | ./node_modules/.bin/coveralls
deploy:
  provider: npm
  skip_cleanup: true
  email: kkitokkito@gmail.com
  api_key:
    secure: aIo4O2AdWZOZN3dzB7AK3DAwUtNMP5iExcPDK1rvJiySP8A0L4Qu5j3gkHLpAjmMLwy5kSWz8ag7kVnXXKugd7TiHBNUHKgMqaH9Hn2r167z0tCJ0hKBLfvSCandPKVCG2mN3ikjaybXrAzJdpeHkXIrfI5d+nPAsMYwC02uP6GAEFkF+JaVed+CwzR5jgHIDLkQ6Bzlxp0nuGGEFURcXrX7yt8P34kAGBZ9EA5Y515t1z+oykzxkEeFQ+UFJ1HfCIRTo3esXsBGk0U54KX6uPHImQQckJ5crN8tudbtVH1A3/ux6vOYAoY8Asjviqvq3SVj12XBgBoBAal/wvPbu6L5PD9/0gCMQ3xLi/C8FeRvxLCQ7NMQI38IDerfiCO7zgc1ntBaQvbixgAv6jVjW+VFr5urLk+T6J+MwtXgBYELubpM9QvMlR4yE8lCMjDzuGVf3vw2wa2+wT9slKPhnmshNGXSjklcGz+rGPJ+bWin/Qa5s+DRRKDTe5pPy+hYUJnWf+w/JrrV/V6eSB7aHxjpjf01Kod7hiAagANVNARR+oKmmu01aAbg6ZS56BaIqzg2AHXuSIWJKHt1dtv8sw8rQp5Gp/d7F0i2k9u3KfwioHV/Jj413vaSZyY4J3qy9lcJmjvXACn4qQA/icKfqzT5h+z+pxlAmbPEpja/x1Q=
  on:
    tags: true
    repo: kkito/transmission-rpc
